const declaracoes = [
  "1. Porque “eu te amo” nunca será suficiente ",
  "2. Porque a cada dia você me conquista mais e de um jeito novo ",
  "3. Porque a ciência não tem como explicar nosso amor ",
  "4. Porque a gente discute nossos problemas ",
  "5. Porque a nossa história está escrita no tempo e ninguém vai apagar ",
  "6. Porque a sua companhia é melhor que chocolate ",
  "7. Porque a vontade de ficar junto com você me aperta o coração ",
  "8. Porque amor não tem sentido ",
  "9. Porque ao seu lado enfrento o impossível ",
  "10. Porque ao seu lado eu me sinto adulto ",
  "11. Porque ao seu lado eu me sinto criança ",
  "12. Porque ao seu lado eu me sinto único ",
  "13. Porque ao seu lado eu não sinto falta de nada ",
  "14. Porque ao seu lado eu pareço um menininho sonhador",
  "15. Porque ao seu lado eu sou a mais sedutor dos homens",
  "16. Porque ao seu lado parece que o mundo para ",
  "17. Porque ao seu lado sinto que o impossível não existe ",
  "18. Porque ao seu lado tudo fica maravilhoso ",
  "19. Porque aonde quer que eu vá, levo você no olhar",
  "20. Porque cada carinho teu me leva às nuvens ",
  "21. Porque cada dia ao teu lado é um dia único ",
  "22. Porque cada dia que passo ao seu lado é especial e único ",
  "23. Porque cada minuto é muito tempo sem você ",
  "24. Porque com você eu posso ser eu mesmo e não preciso fingir nada ",
  "25. Porque com você eu sou mais divertido ",
  "26. Porque com você eu sou mais meigo ",
  "27. Porque com você eu sou mais sonhador",
  "28. Porque com você eu sou mais tranquilo ",
  "29. Porque com você meus medos diminuem ",
  "30. Porque de qualquer jeito seu sorriso vai ser meu raio de sol ",
  "31. Porque dói estar sem você ",
  "32. Porque dói te ver sofrer ",
  "33. Porque é ao seu lado tenho vivido os melhores momentos da minha vida ",
  "34. Porque é bom acordar e lembrar de você ",
  "35. Porque é bom dormir e sonhar com você ",
  "36. Porque é gostoso brincar com você ",
  "37. Porque é legal ser irritado por você",
  "38. Porque é legal te irritar",
  "39. Porque é lindo vê-la sorrir ",
  "40. Porque é maravilhoso andar de mãos dadas com você ",
  "41. Porque é maravilhoso pensar com você, rir com você ",
  "42. Porque é só você que eu amo ",
  "43. Porque é só você que eu quero pra sempre ",
  "44. Porque é tão bom te amar ",
  "45. Porque é tão fácil te amar ",
  "46. Porque é um privilégio ter o seu amor ",
  "47. Porque é você quem faz virar meu mundo ",
  "48. Porque estamos conectados ",
  "49. Porque estes motivos são só nossos ",
  "50. Porque estou aprendendo a ser otimista",
  "51. Porque eu amo a forma como você me ama ",
  "52. Porque eu amo a sua voz ",
  "53. Porque eu amo amar você ",
  "54. Porque eu amo andar com você me abraçando ",
  "55. Porque eu amo andar de mãos dadas ",
  "56. Porque eu amo conversar com você ",
  "57. Porque eu amo dançar com você",
  "58. Porque eu amo dormir com você em meus braços ",
  "59. Porque eu amo fazer qualquer coisa com você ",
  "60. Porque eu amo fazer você sorrir ",
  "61. Porque eu amo ouvir músicas que me lembram você",
  "62. Porque eu amo seu sorriso ",
  "63. Porque eu choro com você ",
  "64. Porque eu confio em você ",
  "65. Porque eu confio em você de olhos fechados ",
  "66. Porque eu confio totalmente em você ",
  "67. Porque eu conto os dias e conto as horas pra te ver ",
  "68. Porque eu conto tudo pra você sempre, de qualquer jeito",
  "69. Porque eu desejo escutar a sua voz ",
  "70. Porque eu desejo sentir seu calor ",
  "71. Porque eu desejo tocar seu rosto ",
  "72. Porque eu divido a minha vida com você ",
  "73. Porque eu divido as minhas alegrias com você ",
  "74. Porque eu divido minhas tristezas com você ",
  "75. Porque eu faço tudo pra te ver feliz ",
  "76. Porque eu falo de tudo com você ",
  "77. Porque eu fico pensando no nosso futuro juntos ",
  "78. Porque eu gosto de estar com você ",
  "79. Porque eu gosto de ficar abraçadinho sem dizer nada ",
  "80. Porque eu gosto de ir a qualquer lugar com você",
  "81. Porque eu gosto de ir à quadra e a praça com você ",
  "82. Porque eu gosto de sentir o calor dos seus abraços ",
  "83. Porque eu gosto de ser criança com você ",
  "84. Porque eu gosto de te amar ",
  "85. Porque eu gosto de te ver feliz ",
  "86. Porque eu gosto do seu jeito de ser",
  "87. Porque eu me apaixonei pelo seu olhar ",
  "88. Porque eu me arrumo pensando em você ",
  "89. Porque eu me desmancho por você ",
  "90. Porque eu me orgulho de você ",
  "91. Porque eu me preocupo com seus problemas ",
  "92. Porque eu me sinto bem com você ",
  "93. Porque eu me sinto seguro com você ",
  "94. Porque eu não brigo quando você se atrasa ",
  "95. Porque eu não consigo ficar sem você na minha vida ",
  "96. Porque eu não consigo melhores palavras pra dizer que te amo ",
  "97. Porque eu não consigo te esquecer ",
  "98. Porque eu não existo longe de você, e a solidão é meu pior castigo ",
  "99. Porque eu não existo sem você ",
  "100. Porque eu não gosto de te fazer sofrer ",
  "101. Porque eu não gosto de te ver triste ",
  "102. Porque eu não me canso de dizer que te amo ",
  "103. Porque eu não me canso de te amar ",
  "104. Porque eu não quero viver sem você ",
  "105. Porque eu não sei como você se apaixonou por mim ",
  "106. Porque eu não sei viver sem seu amor ",
  "107. Porque eu não vivo sem você um segundo ",
  "108. Porque eu odeio me despedir de você ",
  "109. Porque eu penso em você ao almoçar ",
  "110. Porque eu perdi a conta dos presentes que você me deu ",
  "111. Porque eu posso contar com você sempre ",
  "112. Porque eu posso contar tudo pra você sempre ",
  "113. Porque eu posso sentir o seu cheiro em pensamento ",
  "114. Porque eu preciso de você ",
  "115. Porque eu preciso do seu amor",
  "116. Porque eu quero conhecer o mundo ao seu lado ",
  "117. Porque eu quero descobrir tudo ao seu lado ",
  "118. Porque eu quero fazê-lo feliz para sempre ",
  "119. Porque eu quero mais fotos nossas ",
  "120. Porque eu sei coisas sobre você que ninguém mais sabe ",
  "121. Porque eu sei que você me ama ",
  "122. Porque eu sei que você não me troca por nada nesse mundo ",
  "123. Porque eu sinto a tua ausência ",
  "124. Porque eu sinto saudade da sua voz",
  "125. Porque eu sinto saudade do seu olhar ",
  "126. Porque eu sinto saudade do seu sorriso ",
  "127. Porque eu sinto saudades de quando estamos juntos ",
  "128. Porque eu sinto seu amor ",
  "129. Porque eu sinto seu amor verdadeiro ",
  "130. Porque eu sinto seu beijo sincero ",
  "131. Porque eu só desejo você ",
  "132. Porque eu só tenho você, e é a única pessoa que eu posso contar ",
  "133. Porque eu sonho em construir uma família ao seu lado ",
  "134. Porque eu sou o homem da sua vida ",
  "135. Porque eu sou o homem mais amado no mundo ",
  "136. Porque eu sou apaixonado por você ",
  "137. Porque eu sou louco por você ",
  "138. Porque eu sou romântico com você",
  "139. Porque eu sou só seu ",
  "140. Porque eu sou seu e quero ser só seu por toda nossa vida ",
  "141. Porque eu sou seu pra sempre ",
  "142. Porque eu te acompanho quando você quer comer e eu não ",
  "143. Porque eu te admiro muito ",
  "144. Porque eu te amo de um jeito louco ",
  "145. Porque eu te amo e ninguém muda isso ",
  "146. Porque eu te amo mesmo quando me deixa preocupado ",
  "147. Porque eu te amo profundamente ",
  "148. Porque eu te conheço muito bem ",
  "149. Porque eu te escolhi ",
  "150. Porque eu te quero a todo o momento ",
  "151. Porque eu tenho orgulho de você ",
  "152. Porque eu tenho vontade de te amar ",
  "153. Porque existe um lado meu que só você conhece ",
  "154. Porque existe um lado seu que só eu conheço ",
  "155. Porque existe uma química única e especial entre nós ",
  "156. Porque existem n motivos para eu te amar sempre cada vez mais e mais ",
  "157. Porque fazer coisas com você é divertido ",
  "158. Porque fecho os olhos pra não ver passar o tempo ",
  "159. Porque ficar abraçadinha com você é maravilhoso ",
  "160. Porque fomos feitos um para o outro ",
  "161. Porque já me fez sentir coisas ",
  "162. Porque já te fiz sentir coisas ",
  "163. Porque juntos fazemos loucuras ",
  "164. Porque juntos podemos fazer várias coisas e ter bons momentos ",
  "165. Porque juntos podemos não fazer nada e ter bons momentos ",
  "166. Porque juntos somos como queijo com goiabada ",
  "167. Porque juntos temos um sonho ",
  "168. Porque juntos vivemos momentos intensos ",
  "169. Porque me aconchegar em você é tão gostoso ",
  "170. Porque me faz confiar em você ",
  "171. Porque me faz rir quando eu quero chorar ",
  "172. Porque mesmo longe eu sinto você perto ",
  "173. Porque mesmo quando estou errado você fica ao meu lado ",
  "174. Porque mesmo quando eu me atraso seu amor é igual ",
  "175. Porque meu amor é só seu ",
  "176. Porque meu amor é todo seu, e somente seu ",
  "177. Porque meu amor por você é único ",
  "178. Porque meu coração é todo seu, e somente seu ",
  "179. Porque meu desejo é fazer você tão feliz quanto você me faz ",
  "180. Porque meu futuro sem você não existe ",
  "181. Porque minha mãe gosta de você ",
  "182. Porque nada muda o que eu sinto por você ",
  "183. Porque não tem coisa melhor que o seu beijo ",
  "184. Porque nem “eu te amo” ao quadrado não será suficiente ",
  "185. Porque nem “eu te amo” ao cubo não será suficiente",
  "186. Porque ninguém é igual a você ",
  "187. Porque ninguém vai te amar como eu te amo ",
  "188. Porque nos divertimos juntos ",
  "189. Porque nós estamos crescendo juntos ",
  "190. Porque nós nos completamos ",
  "191. Porque nós nos divertimos juntos ",
  "192. Porque nós podemos caminhar juntos, rumo a um mesmo alvo ",
  "193. Porque nos seus braços sinto-me muito bem",
  "194. Porque nós somos cúmplices um do outro ",
  "195. Porque nós somos o casal mais lindo ",
  "196. Porque nós temos amadurecido juntos ",
  "197. Porque nós vamos realizar todas as nossas fantasias ",
  "198. Porque nós vamos realizar todos os nossos sonhos ",
  "199. Porque nossa história de amor é linda ",
  "200. Porque nossa história é diferente ",
  "201. Porque nosso amor é indescritível ",
  "202. Porque nosso amor é maior que o infinito ",
  "203. Porque nosso amor é maravilhoso ",
  "204. Porque nosso amor é perfeito ",
  "205. Porque nosso amor é sincero ",
  "206. Porque nosso amor é verdadeiro ",
  "207. Porque nosso amor faz o meu mundo girar ",
  "208. Porque nosso amor não tem medidas ",
  "209. Porque nosso amor nunca vai acabar ",
  "210. Porque nosso namoro é perfeito ",
  "211. Porque o amor é suficiente ",
  "212. Porque o que é pra ser nosso ninguém tira ",
  "213. Porque o seu beijo é doce e repleto de ternura",
  "214. Porque o seu beijo é intenso e apaixonante ",
  "215. Porque o seu beijo é o seu beijo ",
  "216. Porque o seu beijo me faz perder o chão ",
  "217. Porque o seu olhar me conquistou ",
  "218. Porque o toque dos seus lábios é intenso ",
  "219. Porque os seus abraços me confortam ",
  "220. Porque para mim não há a menor possibilidade de amar outro ",
  "221. Porque passamos por momentos ruins, mas juntos superamos ",
  "222. Porque penso em você antes de dormir ",
  "223. Porque penso em você ao acordar ",
  "224. Porque penso em você ao escutar uma música ",
  "225. Porque penso em você ao me arrumar ",
  "226. Porque penso em você ao tomar banho ",
  "227. Porque penso em você assim que vai embora ",
  "228. Porque penso em você de manhã ",
  "229. Porque penso em você de tarde ",
  "230. Porque penso em você de noite",
  "231. Porque penso em você quando estou indo te ver",
  "232. Porque penso em você toda hora ",
  "233. Porque qualquer coisa com você é uma delícia ",
  "234. Porque qualquer coisa que eu vista me lembra você ",
  "235. Porque quando eu estou irritante, você me perdoa por estar assim ",
  "236. Porque quando eu te vejo meu coração dispara ",
  "237. Porque quando fecho os olhos é você que eu vejo ",
  "238. Porque quando me entristece, pede perdão ",
  "239. Porque quando me olha o mundo para só para nós",
  "240. Porque quando quando vou dormir peço pra Deus nos abençoar",
  "241. Porque quando você está chata você pede desculpa por estar assim ",
  "242. Porque quero ter mais tempo com você ",
  "243. Porque sair sem você não tem graça ",
  "244. Porque se eu ficar sem teu amor, eu piro ",
  "245. Porque se ficar sem meu amor, você pira ",
  "246. Porque se isso não é amor, o que mais pode ser? ",
  "247. Porque sei que não preciso esconder nada de você ",
  "248. Porque sem você não sei viver ",
  "249. Porque sem você não serei completamente feliz ",
  "250. Porque sem você sou incompleto ",
  "251. Porque sem você tudo perde a graça",
  "252. Porque sem você vai me faltar um pedaço ",
  "253. Porque sempre é sincero comigo ",
  "254. Porque sempre que precisei você não me faltou ",
  "255. Porque sempre sabe quando estou triste precisando de você ",
  "256. Porque seu abraço me conforta ",
  "257. Porque seu amor é toda minha, e somente minha ",
  "258. Porque seu coração é todo meu, e somente meu ",
  "259. Porque seu olhar diz que me ama ",
  "260. Porque seu olhar é profundo ",
  "261. Porque seu olhar está sempre me reconquistando",
  "262. Porque seu olhar me faz perder o sentido ",
  "263. Porque seus beijos curam minhas dores ",
  "264. Porque seus beijos são uma delícia ",
  "265. Porque seus lábios são doces como o mel ",
  "266. Porque seus lábios têm sabor de mel ",
  "267. Porque sinto que pertenço a você ",
  "268. Porque só sobrou o amor ",
  "269. Porque só você é linda assim",
  "270. Porque só você me faz sorrir sempre ",
  "271. Porque só você me faz te amar tanto desse jeito ",
  "272. Porque só você pode me dar o que preciso ",
  "273. Porque só você pra me aguentar todo esse tempo",
  "274. Porque só você pra me amar tanto desse jeito ",
  "275. Porque só você pra me dizer tudo o que quero ouvir ",
  "276. Porque só você pra me fazer sorrir quando estou mal humorada ",
  "277. Porque só você sabe o quanto eu te amo ",
  "278. Porque sou um peixinho fora d’água sem você ",
  "279. Porque amo fofocar com você",
  "280. Porque sua voz é linda ",
  "281. Porque superamos juntos várias crises ",
  "282. Porque te amar é divertido ",
  "283. Porque te amar é mais do que demais ",
  "284. Porque te amar é maravilhoso ",
  "285. Porque te amar me faz bem ",
  "286. Porque te amar me faz muito bem ",
  "287. Porque temos fotos juntos ",
  "288. Porque temos ótimos momentos juntos ",
  "289. Porque temos sonhos ",
  "290. Porque teu amor me faz forte ",
  "291. Porque os gestos valem mais que mil palavras ",
  "292. Porque um futuro sem você não seria meu ",
  "293. Porque viver sem amor tem menos sentido ainda ",
  "294. Porque viver sem você não tem graça ",
  "295. Porque você acredita em mim ",
  "296. Porque você aprendeu o que me faz bem e sempre procura me agradar",
  "297. Porque você brinca comigo ",
  "298. Porque você concorda comigo ",
  "299. Porque você confia em mim ",
  "300. Porque você conhece o meu amor ",
  "301. Porque você continua me conquistando ",
  "302. Porque você demonstra o seu amor todos os dias",
  "303. Porque você discorda de mim ",
  "304. Porque você divide as suas tristezas comigo ",
  "305. Porque você é a minha cara-metade ",
  "306. Porque você é a pessoa mais importante pra mim",
  "307. Porque você é alegre ",
  "308. Porque você é amorosa comigo ",
  "309. Porque você é carinhosa ",
  "310. Porque você é completamente diferente de mim",
  "311. Porque você é cúmplice ",
  "312. Porque você é divertida ",
  "313. Porque você é e sempre será minha melhor amiga ",
  "314. Porque você é engraçada",
  "315. Porque você é incrível ",
  "316. Porque você torna meus dias mais alegres",
  "317. Porque você é mais do que sonhei pra mim ",
  "318. Porque você é meu amor perfeito no meu peito ",
  "319. Porque você é meu melhor amiga ",
  "320. Porque você é meu pensamento constante ",
  "321. Porque você é meu pensamento de todos os dias ",
  "322. Porque você é a minha Cinderela",
  "323. Porque você me elogia ",
  "324. Porque você me enche de presentes ",
  "325. Porque você me ensina a rir das coisas da vida",
  "326. Porque você me ensina coisas incríveis ",
  "327. Porque você me ensinou a perceber os segredos desse amor ",
  "328. Porque você me ensinou a ter um humor melhor ",
  "329. Porque você me entende ",
  "330. Porque você me escolheu ",
  "331. Porque você me escuta e me acalma ",
  "332. Porque você me espera sempre que preciso ",
  "333. Porque você me esquenta no frio ",
  "334. Porque você me estende a mão antes mesmo de precisar pedir sua ajuda ",
  "335. Porque você me faz bem ",
  "336. Porque você me faz chorar de alegria ",
  "337. Porque você me faz chorar de emoção ",
  "338. Porque você me faz cometer loucuras ",
  "339. Porque você me faz feliz ",
  "340. Porque você me faz mais feliz a cada dia ",
  "341. Porque você me faz perder a cabeça ",
  "342. Porque você me faz perder a noção do tempo e do mundo ",
  "343. Porque você me faz refletir e questionar sobre as coisas de vida ",
  "344. Porque você me faz rir a qualquer hora ",
  "345. Porque você me faz sentir o homem mais especial do mundo ",
  "346. Porque você me faz sentir a sua ausência ",
  "347. Porque você me faz sonhar acordado ",
  "348. Porque você me faz sonhar dormindo ",
  "349. Porque você me faz te amar cada vez mais ",
  "350. Porque você me faz te amar como eu nunca imaginei amar alguém ",
  "351. Porque você me incentiva ",
  "352. Porque você me inspira ",
  "353. Porque você me olha de um jeito especial ",
  "354. Porque você me perdoa quando eu erro ",
  "355. Porque você me refresca no calor ",
  "356. Porque você me repreende às vezes ",
  "357. Porque você me respeita ",
  "358. Porque você me trata como um principe ",
  "359. Porque você merece o meu amor ",
  "360. Porque você não cansa de dizer que me ama ",
  "361. Porque você não é egoísta ",
  "362. Porque você nunca me desampara quando estou com problemas",
  "363. Porque você não me deixa cair ",
  "364. Porque você não me deixa me sentir sozinho ",
  "365. Porque você não precisa falar nada pra dizer que ama",
];

function todasDeclarações(array) {
  let element2 = document.getElementById("text2");
  element2.innerText += "Dias:\n";
  for (let index = 0; index < array.length; index++) {
    element2.innerText += array[index] + "\n";
  }
}

todasDeclarações(declaracoes);
